# coding: utf-8

"""
    Library Management API

    API quản lý thư viện — cho phép thực hiện CRUD trên sách và thành viên.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from library_api.apis.books_api import router as BooksApiRouter
from library_api.apis.members_api import router as MembersApiRouter

app = FastAPI(
    title="Library Management API",
    description="API quản lý thư viện — cho phép thực hiện CRUD trên sách và thành viên.",
    version="1.0.0",
)

app.include_router(BooksApiRouter)
app.include_router(MembersApiRouter)
